INSERT INTO customer (id, first_name, last_name) values(default,'Sagar', 'Rane');
INSERT INTO MOBILE_NUMBERS (MOBILE_NUMBER, CUST_ID) VALUES ('9222222222',1);
INSERT INTO MOBILE_NUMBERS (MOBILE_NUMBER, CUST_ID) VALUES ('9333333333',1);
INSERT INTO customer (id, first_name, last_name) values(default,'Snehal', 'Navale');
INSERT INTO MOBILE_NUMBERS (MOBILE_NUMBER, CUST_ID) VALUES ('9444444444',2);
INSERT INTO MOBILE_NUMBERS (MOBILE_NUMBER, CUST_ID) VALUES ('9555555555',2);
INSERT INTO MOBILE_NUMBERS (MOBILE_NUMBER, CUST_ID) VALUES ('9666666666',2);